language: python
python:
    - "3.6"
env:
  - DJANGO_VERSION=2.1.3
  - DJANGO_SETTINGS_MODULE=fast_food_api.settings

install:
    - pip install -r requirements.txt

script:
    -python fast_food_api/manage.py test

